server:
  port: 9090

spring:
  application:
    name: ApiGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservice-realm
          jwk-set-uri: http://keycloak:8080/realms/microservice-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://StudentService
          predicates:
            - Path=/api/v1/student/**
eureka:
  client:
    service-url:
      default-zone: http://application:8761/eureka

