server:
  port: 9091

spring:
  application:
    name: StudentService
  datasource:
    username: admin
    password: secret
    url: jdbc:postgresql://localhost:5433/student

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

